force-app/main/default/objects/Help_Message__c/Help_Message__c.object-meta.xml
<CustomObject>
    <description>This object is used for storing dynamically accessible help / guidance messages for display within the application</description>
    <label>Help Message</label>
    <nameField>
        <label>Help Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Help_Message__c/fields/Custom_Filter_Logic__c.field-meta.xml
<CustomField>
    <fullName>Custom_Filter_Logic__c</fullName>
    <inlineHelpText>Use this field to apply custom filter logic based on SOQL principles</inlineHelpText>
    <label>Custom Filter Logic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Filter_Type__c.field-meta.xml
<CustomField>
    <fullName>Filter_Type__c</fullName>
    <inlineHelpText>Determine the filter type to be used with your filters</inlineHelpText>
    <label>Filter Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Records_Valid_For__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>CUSTOM</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>This confirms what the order of display is for the help messages</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Records_Valid_For__c.field-meta.xml
<CustomField>
    <fullName>Records_Valid_For__c</fullName>
    <inlineHelpText>This confirms if filters are being applied to this help message, if you select all then it will appear at all time on the record</inlineHelpText>
    <label>Records Valid For</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>By Filter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Help_Message_Filter__c/Help_Message_Filter__c.object-meta.xml
<CustomObject>
    <description>This object provides the ability to filter records based on specific values and ensure the right help is provided at the right time.</description>
    <label>Help Message Filter</label>
    <nameField>
        <label>Help Message Filter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Message Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Help_Message_Filter__c/fields/Help_Message__c.field-meta.xml
<CustomField>
    <fullName>Help_Message__c</fullName>
    <inlineHelpText>This is the specific help message that this filter is being applied against</inlineHelpText>
    <label>Help Message</label>
    <referenceTo>Help_Message__c</referenceTo>
    <relationshipLabel>Help Message Filters</relationshipLabel>
    <relationshipName>Help_Message_Filters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Help_Message_Filter__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HelpMessageConfigurationFilters.cls
/**
 * @description       : Controller class to support with the management of help message filters during configuration
 * @author            : daniel@hyphen8.com
 * @last modified on  : 21/02/2024
 * @last modified by  : daniel@hyphen8.com
**/
public with sharing class HelpMessageConfigurationFilters {

    /**
    * @description              method that will delete a filter when requested from the configuration component and then reorder existing items
    * @param                    messageFilterId 
    * @return                   String 
    **/
    @AuraEnabled
    public static String deleteConditionFilter(String messageFilterId){
        try {
            Help_Message_Filter__c messageFilter = [SELECT Id, Help_Message__c, Order__c 
                                                                FROM Help_Message_Filter__c 
                                                                WHERE Id=:messageFilterId 
                                                                WITH SECURITY_ENFORCED 
                                                                LIMIT 1];
            List<Help_Message_Filter__c> existingFiltersToUpdate = new List<Help_Message_Filter__c>();
            Integer orderUpdate = 1;
            for(Help_Message_Filter__c existingFilter:[SELECT Id, Order__c 
                                                                    FROM Help_Message_Filter__c 
                                                                    WHERE Id!=:messageFilterId 
                                                                    AND Help_Message__c=:messageFilter.Help_Message__c 
                                                                    WITH SECURITY_ENFORCED 
                                                                    ORDER BY Order__c DESC]){
                System.debug(existingFilter);
                existingFilter.Order__c = orderUpdate;
                orderUpdate = orderUpdate + 1;
                existingFiltersToUpdate.add(existingFilter);
            }

            Help_Message__c currentHelpMessage = [SELECT Id, Records_Valid_For__c, Filter_Type__c
                                                        FROM Help_Message__c 
                                                        WHERE Id=:messageFilter.Help_Message__c 
                                                        WITH SECURITY_ENFORCED 
                                                        LIMIT 1];
            if(currentHelpMessage.Records_Valid_For__c == 'By Filter' && currentHelpMessage.Filter_Type__c == 'CUSTOM'){
                currentHelpMessage.Custom_Filter_Logic__c = '';
                update currentHelpMessage;
            }
            update existingFiltersToUpdate;
            delete messageFilter;
            
            return '';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }


    /**
    * @description              method that is used to support with the saving of values on a specific help message filter record
    * @param                    helpMessageFilterId 
    * @param                    fieldAPIName 
    * @param                    filterValue 
    * @return                   String 
    **/
    @AuraEnabled
    public static String handleSaveFilterValues(String helpMessageFilterId, String fieldAPIName, String filterValue){
        try {
            Help_Message_Filter__c helpMessageFilter = [SELECT Id 
                                                            FROM Help_Message_Filter__c 
                                                            WHERE Id=:helpMessageFilterId 
                                                            WITH SECURITY_ENFORCED 
                                                            LIMIT 1];
            helpMessageFilter.put(fieldAPIName, filterValue);
            update helpMessageFilter;
            return '';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}