force-app/main/default/objects/Help_Message__c/Help_Message__c.object-meta.xml
<CustomObject>
    <description>This object is used for storing dynamically accessible help / guidance messages for display within the application</description>
    <label>Help Message</label>
    <nameField>
        <label>Help Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Help_Message__c/fields/Custom_Filter_Logic__c.field-meta.xml
<CustomField>
    <fullName>Custom_Filter_Logic__c</fullName>
    <inlineHelpText>Use this field to apply custom filter logic based on SOQL principles</inlineHelpText>
    <label>Custom Filter Logic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Filter_Type__c.field-meta.xml
<CustomField>
    <fullName>Filter_Type__c</fullName>
    <inlineHelpText>Determine the filter type to be used with your filters</inlineHelpText>
    <label>Filter Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Records_Valid_For__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>CUSTOM</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Is_Draft__c.field-meta.xml
<CustomField>
    <fullName>Is_Draft__c</fullName>
    <formula>ISPICKVAL(Status__c, &apos;Draft&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Draft</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Likes__c.field-meta.xml
<CustomField>
    <fullName>Likes__c</fullName>
    <inlineHelpText>This field will display the number of people who have liked or found this help message useful. It will only display data if your administrators has configured your application to support tracking of this information,</inlineHelpText>
    <label>Likes</label>
    <summaryForeignKey>Help_Message_Like__c.Help_Message__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <inlineHelpText>This is the body of the help / guidance message that will appear on the record</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Message_Title__c.field-meta.xml
<CustomField>
    <fullName>Message_Title__c</fullName>
    <inlineHelpText>This is the message that will as the header / title for the help message</inlineHelpText>
    <label>Message Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <inlineHelpText>This confirms what the order of display is for the help messages</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Record_SObjectType__c.field-meta.xml
<CustomField>
    <fullName>Record_SObjectType__c</fullName>
    <inlineHelpText>Please provide a value Object API Name in here, this determine what record the message should appear on.</inlineHelpText>
    <label>Record SObjectType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Records_Valid_For__c.field-meta.xml
<CustomField>
    <fullName>Records_Valid_For__c</fullName>
    <inlineHelpText>This confirms if filters are being applied to this help message, if you select all then it will appear at all time on the record</inlineHelpText>
    <label>Records Valid For</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>By Filter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Unpublished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Views__c.field-meta.xml
<CustomField>
    <fullName>Views__c</fullName>
    <inlineHelpText>This field will display the number of views that a Help Message has had, it will only populate data if analytics has been configured by your system administrator.</inlineHelpText>
    <label>Views</label>
    <summaryForeignKey>Help_Message_View__c.Help_Message__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Help_Message_Configuration__c/Help_Message_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom settings that are used to support with the configuration of enabling Analytics on your Help Messages</description>
    <label>Help Message Configuration</label>
</CustomObject>

force-app/main/default/objects/Help_Message_Configuration__c/fields/Enable_Analytics__c.field-meta.xml
<CustomField>
    <fullName>Enable_Analytics__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When enabled this will start logging views of help messages, it will only log 1 view per person per day</inlineHelpText>
    <label>Enable Analytics</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Help_Message_Configuration__c/fields/Enabled_Found_Useful__c.field-meta.xml
<CustomField>
    <fullName>Enabled_Found_Useful__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When enabled this ensure that someone pressing the like button is logged to support with reporting on popularity of a help message</inlineHelpText>
    <label>Enabled Found Useful</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Help_Message_Filter__c/Help_Message_Filter__c.object-meta.xml
<CustomObject>
    <description>This object provides the ability to filter records based on specific values and ensure the right help is provided at the right time.</description>
    <label>Help Message Filter</label>
    <nameField>
        <label>Help Message Filter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Message Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Help_Message_Filter__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <inlineHelpText>This is the salesforce field API name</inlineHelpText>
    <label>Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Help_Message_Filter__c/fields/Field_Operator__c.field-meta.xml
<CustomField>
    <fullName>Field_Operator__c</fullName>
    <inlineHelpText>This determines if the value you are providing matches or does not match</inlineHelpText>
    <label>Field Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>equals</fullName>
            </value>
            <value>
                <fullName>not equal to</fullName>
            </value>
            <value>
                <fullName>greater than</fullName>
            </value>
            <value>
                <fullName>greater than or equals</fullName>
            </value>
            <value>
                <fullName>less than</fullName>
            </value>
            <value>
                <fullName>less than or equals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Help_Message_Filter__c/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <inlineHelpText>This is the field value that we are comparing or checking against</inlineHelpText>
    <label>Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Help_Message_Filter__c/fields/Help_Message__c.field-meta.xml
<CustomField>
    <fullName>Help_Message__c</fullName>
    <inlineHelpText>This is the specific help message that this filter is being applied against</inlineHelpText>
    <label>Help Message</label>
    <referenceTo>Help_Message__c</referenceTo>
    <relationshipLabel>Help Message Filters</relationshipLabel>
    <relationshipName>Help_Message_Filters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Help_Message_Filter__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Help_Message_Filter__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>This determines the type of field</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Record Field</fullName>
                <default>true</default>
                <label>Record Field</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Help_Message_Like__c/Help_Message_Like__c.object-meta.xml
<CustomObject>
    <description>This object is used to store who has liked or found this help message useful, it is then aggregated onto the Help Message record. You will need to configure the custom settings for this to be used.</description>
    <label>Help Message Like</label>
    <nameField>
        <displayFormat>HMLID{000000000}</displayFormat>
        <label>Help Message Like Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Message Likes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Help_Message_Like__c/fields/Help_Message__c.field-meta.xml
<CustomField>
    <fullName>Help_Message__c</fullName>
    <label>Help Message</label>
    <referenceTo>Help_Message__c</referenceTo>
    <relationshipLabel>Help Message Likes</relationshipLabel>
    <relationshipName>Help_Message_Likes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Help_Message_View__c/Help_Message_View__c.object-meta.xml
<CustomObject>
    <description>Object used to support analytics within the application, when configured correctly each help message will store who has view the help message and aggregate a total views onto the help message</description>
    <label>Help Message View</label>
    <nameField>
        <displayFormat>HMVID{000000000}</displayFormat>
        <label>Help Message View Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Help Message Views</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Help_Message_View__c/fields/Help_Message__c.field-meta.xml
<CustomField>
    <fullName>Help_Message__c</fullName>
    <label>Help Message</label>
    <referenceTo>Help_Message__c</referenceTo>
    <relationshipLabel>Help Message Views</relationshipLabel>
    <relationshipName>Help_Message_Views</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/HelpMessageController.cls
/**
 * @description       : Controller for the in record help message component
 *                      will return dynamically messages driven by the type of record and filters on the record
 * @author            : daniel@hyphen8.com
 * @last modified on  : 14-02-2024
 * @last modified by  : daniel@hyphen8.com
**/

public with sharing class HelpMessageController {

    public static Set<String> filterFields = new Set<String>();
    private static Help_Message_Configuration__c helpConfiguration;
    private static Help_Message_Like__c userLike;

    /**
    * @description          method to support with the submission of likes against a help message
    * @param                helpMessageId 
    **/
    @AuraEnabled
    public static void submitLike(String helpMessageId){
        try {
            getHelpConfiguration();
            getUserLikeRecord(helpMessageId);
            String helpMessageStatus = helpMessageStatus(helpMessageId);
            if(null == userLike && helpMessageStatus == 'Published' && null != helpConfiguration && helpConfiguration.Enabled_Found_Useful__c){
                Help_Message_Like__c newLike = new Help_Message_Like__c();
                newLike.Help_Message__c = helpMessageId;
                insert newLike;
            } else if(null != userLike){
                delete userLike;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
    * @description          method to generate the view entry record to support analytics
    * @param                helpMessageId 
    **/
    @AuraEnabled
    public static void generateViewEntry(String helpMessageId){
        try {
            getHelpConfiguration();
            Boolean hasViewLoggedToday = hasViewHelpToday(helpMessageId);
            String helpMessageStatus = helpMessageStatus(helpMessageId);
            if(!hasViewLoggedToday && null != helpConfiguration && helpConfiguration.Enable_Analytics__c && helpMessageStatus == 'Published'){
                Help_Message_View__c helpMessageView = new Help_Message_View__c();
                helpMessageView.Help_Message__c = helpMessageId;
                insert helpMessageView;
            }
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }

    /**
    * @description          method to pull out the help configuration analytics custom settings
    **/
    private static void getHelpConfiguration(){
        helpConfiguration = Help_Message_Configuration__c.getOrgDefaults();
    }

    /**
    * @description          method to get the help message status
    * @param                helpMessageId 
    * @return               String 
    **/
    private static String helpMessageStatus(String helpMessageId){
        return [SELECT Status__c 
                        FROM Help_Message__c 
                        WHERE Id=:helpMessageId
                        LIMIT 1].Status__c;
    }

    /**
    * @description          method to check and confirm if the user has viewed the help message today
    * @param                helpMessageId 
    * @return               Boolean 
    **/
    private static Boolean hasViewHelpToday(String helpMessageId){
        try {
            Help_Message_View__c helpMessageView = [SELECT Id FROM Help_Message_View__c
                                                            WHERE CreatedById=:UserInfo.getUserId()
                                                            AND Help_Message__c=:helpMessageId
                                                            AND CreatedDate= TODAY
                                                            LIMIT 1];
            return true;
        } catch (Exception e){
            return false;
        }
    }
    
    /**
    * @description          method to get the current users like record if it exists
    * @param                helpMessageId 
    **/
    private static void getUserLikeRecord(String helpMessageId){
        try {
            userLike = [SELECT Id 
                            FROM Help_Message_Like__c 
                            WHERE CreatedById=:UserInfo.getUserId() 
                            AND Help_Message__c=:helpMessageId
                            LIMIT 1];
        } catch (Exception e){
            // no like is found so no action required
        }
    }
    /**
     * @description     method that will support the handling of publishing and unpublishing actions
     * @param           recordId
     * @param           status 
     * @return          string 
    */
    @SuppressWarnings('PMD.ApexCRUDViolation')
    @AuraEnabled
    public static String changeMessageStatus(string recordId, string status){
        String returnmessage;
        
        try {
            Help_Message__c helpmessage = [SELECT ID, Status__c 
                                                    FROM Help_Message__c 
                                                    WHERE ID=:recordId
                                                    LIMIT 1];
            helpmessage.Status__c = status;
            update helpmessage;
            returnmessage = 'You have successfully changed the status';
        
        } catch(Exception e) {
        
            returnmessage = 'We encountered an error > ' + e.getMessage();
        
        }

        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
            gen.writeStringField('message', returnmessage);
        gen.writeEndObject();
        return gen.getAsString();
    }

    /**
     * @description     method to confirm if the current user is a member of the editor permission set
     * @return          boolean
    */
    @SuppressWarnings('PMD.ApexCRUDViolation')
    @AuraEnabled
    public static String canViewRecordActions(){
        ID userID = UserInfo.getUserId();
        Boolean returnValue;
        String message = '';
        try {
            ID helpMessageEditorPermissionSet = [SELECT PermissionSetId 
                                                            FROM PermissionSetAssignment 
                                                            WHERE PermissionSet.Name = 'Help_Message_Editor' AND AssigneeId=:UserId].PermissionSetId;
            returnvalue = true;
        } catch (Exception e){
            system.debug(e.getMessage());
            message = e.getMessage();
            returnValue = false;
        }

        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
            gen.writeBooleanField('success', returnvalue);
            gen.writeStringField('message', message);
        gen.writeEndObject();
        return gen.getAsString();
    }


    /**
     * @description     simple help to confirm what statuses we should be looking for based on the current user access the help messages
     * @param           userId string 
     * @return          List<String>
    */
    @SuppressWarnings('PMD.ApexCRUDViolation')
    public static List<String> getStatusList(string userId){
        List<String> returnlist;
        try {
            ID helpmessageeditorpermissionset = [SELECT PermissionSetId 
                                                        FROM PermissionSetAssignment 
                                                        WHERE PermissionSet.Name = 'Help_Message_Editor' AND AssigneeId=:UserId].PermissionSetId;
            returnlist = new List<String>{'Draft','Published'};
        } catch (Exception e){
            returnlist = new List<String>{'Published'};
        }
        return returnlist;
    }

    /**
     * @description     getHelpMessages Aura method used for pulling in the messages to display based on the recordID we are on
     * @param           recordId
     * @return          List<Help_Message__c>
    */
    @SuppressWarnings('PMD.ApexCRUDViolation')
    @AuraEnabled
    public static String getHelpMessages(Id recordId){
        List<String> statuslist = HelpMessageController.getStatusList(UserInfo.getUserId());
        filterFields.add('Id');
        List<Help_Message__c> results = new List<Help_Message__c>();
        List<Help_Message__c> withFilters = new List<Help_Message__c>();
        String sObjectType = recordId.getSobjectType().getDescribe().getName();
        for(Help_Message__c rm : [SELECT Id, Name, Is_Draft__c, Message_Title__c, Message__c, Records_Valid_For__c, Filter_Type__c, Custom_Filter_Logic__c, Status__c, Views__c, Likes__c,   
                                        (SELECT Id, Name, Type__c, Field_Name__c, Field_Operator__c, Field_Value__c 
                                                                    FROM Help_Message_Filters__r 
                                                                    ORDER BY CreatedDate),
                                        (SELECT Id
                                                FROM Help_Message_Likes__r
                                                WHERE CreatedById=:UserInfo.getUserId())
                                        FROM Help_Message__c 
                                        WHERE Record_SObjectType__c=:sObjectType AND Status__c IN:statuslist 
                                        ORDER BY Order__c ASC]) {
            if(rm.Records_Valid_For__c == 'All') {
                results.add(rm);
            } else {
                if(!rm.Help_Message_Filters__r.isEmpty()) {
                    withFilters.add(rm);
                }
            }     
        }
        if(!withFilters.isEmpty()) {
            List<Help_Message__c> filtererlist = HelpMessageHelper.getHelpFilterMessages(withFilters, sObjectType, recordId);
            results.addAll(filtererlist);
        }

        JSONGenerator gen = JSON.createGenerator(true);
        gen.writeStartObject();
            gen.writeFieldName('fieldArray');
            gen.writeStartArray();
            for(String field:filterFields){

                gen.writeStartObject();
                    gen.writeStringField('fieldAPIName', sObjectType + '.' + field);
                gen.writeEndObject();
            }
            gen.writeEndArray();
            gen.writeFieldName('messages');
            gen.writeStartArray();
                for(Help_Message__c helpMessage:results){
                    gen.writeStartObject();
                        gen.writeIdField('id', helpMessage.Id);
                        gen.writeStringField('title', null != helpMessage.Message_Title__c ? helpMessage.Message_Title__c : '');
                        gen.writeStringField('message', null != helpMessage.Message__c ? helpMessage.Message__c : '');
                        gen.writeNumberField('viewCount', helpMessage.Views__c);
                        gen.writeNumberField('likeCount', helpMessage.Likes__c);
                        List<Help_Message_Like__c> helpMessageLikes = helpMessage.Help_Message_Likes__r;
                        if(null != helpMessageLikes && helpMessageLikes.size() > 0){
                            gen.writeStringField('likeLabel', 'Liked');
                            gen.writeBooleanField('likeIsPressed', true);
                            gen.writeStringField('likeButtonAssistiveText', 'Press if you no longer find this help message useful');
                        } else {
                            gen.writeStringField('likeLabel', 'Like');
                            gen.writeBooleanField('likeIsPressed', false);
                            gen.writeStringField('likeButtonAssistiveText', 'Press if you found this help message useful');
                        }
                        gen.writeBooleanField('isDraft', helpMessage.Is_Draft__c);

                    gen.writeEndObject();
                }
            gen.writeEndArray();
        gen.writeEndObject();
        return gen.getAsString();
    }
}