force-app/main/default/objects/Help_Message__c/Help_Message__c.object-meta.xml
<CustomObject>
    <description>This object is used for storing dynamically accessible help / guidance messages for display within the application</description>
    <label>Help Message</label>
    <nameField>
        <label>Help Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Help_Message__c/fields/Filter_Type__c.field-meta.xml
<CustomField>
    <fullName>Filter_Type__c</fullName>
    <inlineHelpText>Determine the filter type to be used with your filters</inlineHelpText>
    <label>Filter Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Records_Valid_For__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AND</fullName>
            </value>
            <value>
                <fullName>OR</fullName>
            </value>
            <value>
                <fullName>CUSTOM</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <inlineHelpText>This is the body of the help / guidance message that will appear on the record</inlineHelpText>
    <label>Message</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Message_Title__c.field-meta.xml
<CustomField>
    <fullName>Message_Title__c</fullName>
    <inlineHelpText>This is the message that will as the header / title for the help message</inlineHelpText>
    <label>Message Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Record_SObjectType__c.field-meta.xml
<CustomField>
    <fullName>Record_SObjectType__c</fullName>
    <inlineHelpText>Please provide a value Object API Name in here, this determine what record the message should appear on.</inlineHelpText>
    <label>Record SObjectType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Help_Message__c/fields/Records_Valid_For__c.field-meta.xml
<CustomField>
    <fullName>Records_Valid_For__c</fullName>
    <inlineHelpText>This confirms if filters are being applied to this help message, if you select all then it will appear at all time on the record</inlineHelpText>
    <label>Records Valid For</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All</fullName>
            </value>
            <value>
                <fullName>By Filter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Help_Message_Filter__c/Help_Message_Filter__c.object-meta.xml
<CustomObject>
    <description>This object provides the ability to filter records based on specific values and ensure the right help is provided at the right time.</description>
    <label>Help Message Filter</label>
    <nameField>
        <label>Help Message Filter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Help Message Filters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Help_Message_Filter__c/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <inlineHelpText>This is the salesforce field API name</inlineHelpText>
    <label>Field Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Help_Message_Filter__c/fields/Field_Operator__c.field-meta.xml
<CustomField>
    <fullName>Field_Operator__c</fullName>
    <inlineHelpText>This determines if the value you are providing matches or does not match</inlineHelpText>
    <label>Field Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>equals</fullName>
            </value>
            <value>
                <fullName>not equal to</fullName>
            </value>
            <value>
                <fullName>greater than</fullName>
            </value>
            <value>
                <fullName>greater than or equals</fullName>
            </value>
            <value>
                <fullName>less than</fullName>
            </value>
            <value>
                <fullName>less than or equals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Help_Message_Filter__c/fields/Field_Value__c.field-meta.xml
<CustomField>
    <fullName>Field_Value__c</fullName>
    <inlineHelpText>This is the field value that we are comparing or checking against</inlineHelpText>
    <label>Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Help_Message_Filter__c/fields/Help_Message__c.field-meta.xml
<CustomField>
    <fullName>Help_Message__c</fullName>
    <inlineHelpText>This is the specific help message that this filter is being applied against</inlineHelpText>
    <label>Help Message</label>
    <referenceTo>Help_Message__c</referenceTo>
    <relationshipLabel>Help Message Filters</relationshipLabel>
    <relationshipName>Help_Message_Filters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Help_Message_Filter__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>This determines the type of field</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Record Field</fullName>
                <default>true</default>
                <label>Record Field</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HelpMessageController_Test.cls
/**
 *  @description        test class for HelpMessageController
 *  @author             hyphen8.com
 *  @date               July 2019
*/
@isTest
public with sharing class HelpMessageController_Test {
 
    @testSetup static void setup() {

        //Valid for all
        Help_Message__c message1 = new Help_Message__c(Name='TestRecordMessage1', Record_SObjectType__c='Account', Records_Valid_For__c='All', Filter_Type__c='N/A', Message_Title__c='TestRecordMessage1', Message__c='TestRecordMessage1');
        insert message1;

        //Valid for filter 'AND'
        Help_Message__c message2 = new Help_Message__c(Name='TestRecordMessage2', Record_SObjectType__c='Account', Records_Valid_For__c='By Filter', Filter_Type__c='AND', Message_Title__c='TestRecordMessage2', Message__c='TestRecordMessage2');
        insert message2;

        List<Help_Message_Filter__c> messageFilters = new List<Help_Message_Filter__c>();

        messageFilters.add(new Help_Message_Filter__c(Help_Message__c=message2.Id, Type__c='Record Field', Field_Name__c='Name', Field_Operator__c='equals', Field_Value__c='TestAccount1'));
        messageFilters.add(new Help_Message_Filter__c(Help_Message__c=message2.Id, Type__c='Record Field', Field_Name__c='Parent.Name', Field_Operator__c='equals', Field_Value__c='DEMO'));

        //Valid for filter 'OR'
        Help_Message__c message3 = new Help_Message__c(Name='TestRecordMessage3', Record_SObjectType__c='Account', Records_Valid_For__c='By Filter', Filter_Type__c='OR', Message_Title__c='TestRecordMessage3', Message__c='TestRecordMessage3');
        insert message3;
        messageFilters.add(new Help_Message_Filter__c(Help_Message__c=message3.Id, Type__c='Record Field', Field_Name__c='Name', Field_Operator__c='equals', Field_Value__c='TestAccount2'));

        insert messageFilters;

    }

    static testMethod void testAccountOne() {

        Account acc = new Account(Name='TestAccount1');
        insert acc;

        List<Help_Message__c> messages = HelpMessageController.getHelpMessages(acc.Id);

        //Should return first and second messages
        System.assertEquals(1, messages.size(), 'Expected number of responses');

        //Check first message name = TestRecordMessage1 and second message name = TestRecordMessage2
        System.assertEquals(messages[0].Name, 'TestRecordMessage1', 'Expected value in response');

    }

    static testMethod void testAccountTwo() {

        Account acc = new Account(Name='TestAccount2');
        insert acc;
    
        List<Help_Message__c> messages = HelpMessageController.getHelpMessages(acc.Id);

        //Should return first and third messages
        System.assertEquals(2, messages.size(), 'Message size matches expected');

        //Check first message name = TestRecordMessage1 and second message name = TestRecordMessage3
        System.assertEquals(messages[0].Name, 'TestRecordMessage1', 'Expected message response from test');
        System.assertEquals(messages[1].Name, 'TestRecordMessage3', 'Expected message response from test');

    }

    static testMethod void testAccountTwoNoPermissionsForDraft() {

        Account acc = new Account(Name='TestAccount2');
        insert acc;

        ID profileid = [SELECT ID FROM Profile WHERE Name=:'Standard User' LIMIT 1].Id;
        String orgId=UserInfo.getOrganizationId(); 
        String dateString=String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomId=Integer.valueOf(Math.rint(Math.random()*1000000)); 
        String uniqueName=orgId+dateString+randomId; 
        User user = new User(
            FirstName = 'DEMO',
            LastName = 'DEMO', 
            Email = uniqueName + '@test' + orgId + '.org', 
            Username = uniqueName + '@test' + orgId + '.org', 
            EmailEncodingKey = 'ISO-8859-1', 
            Alias = uniqueName.substring(18, 23), 
            TimeZoneSidKey = 'GMT',  
            LocaleSidKey = 'en_GB', 
            LanguageLocaleKey = 'en_US', 
            ProfileId  = profileid); 
        insert user;

        system.runAs(user){ 
            List<Help_Message__c> messages = HelpMessageController.getHelpMessages(acc.Id);
            //Should return first and third messages
            System.assertEquals(0, messages.size(), 'Message size matches expected');
        }

    }

}